# Generated by Django 2.1.3 on 2018-12-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('content', models.TextField()),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('create_time', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
