# Generated by Django 2.1.3 on 2018-12-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
